CTA_ROUTES = \
    [{'route_id': '1', 'route_name': 'Bronzeville/Union Station'},
 {'route_id': '2', 'route_name': 'Hyde Park Express'},
 {'route_id': '3', 'route_name': 'King Drive'},
 {'route_id': '4', 'route_name': 'Cottage Grove'},
 {'route_id': 'X4', 'route_name': 'Cottage Grove Express'},
 {'route_id': '5', 'route_name': 'South Shore Night Bus'},
 {'route_id': '6', 'route_name': 'Jackson Park Express'},
 {'route_id': '7', 'route_name': 'Harrison'},
 {'route_id': '8', 'route_name': 'Halsted'},
 {'route_id': '8A', 'route_name': 'South Halsted'},
 {'route_id': '9', 'route_name': 'Ashland'},
 {'route_id': 'X9', 'route_name': 'Ashland Express'},
 {'route_id': '11', 'route_name': 'Lincoln'},
 {'route_id': '12', 'route_name': 'Roosevelt'},
 {'route_id': 'J14', 'route_name': 'Jeffery Jump'},
 {'route_id': '15', 'route_name': 'Jeffery Local'},
 {'route_id': '18', 'route_name': '16th/18th'},
 {'route_id': '19', 'route_name': 'United Center Express'},
 {'route_id': '20', 'route_name': 'Madison'},
 {'route_id': '21', 'route_name': 'Cermak'},
 {'route_id': '22', 'route_name': 'Clark'},
 {'route_id': '24', 'route_name': 'Wentworth'},
 {'route_id': '26', 'route_name': 'South Shore Express'},
 {'route_id': '28', 'route_name': 'Stony Island'},
 {'route_id': '29', 'route_name': 'State'},
 {'route_id': '30', 'route_name': 'South Chicago'},
 {'route_id': '31', 'route_name': '31st'},
 {'route_id': '34', 'route_name': 'South Michigan'},
 {'route_id': '35', 'route_name': '31st/35th'},
 {'route_id': '36', 'route_name': 'Broadway'},
 {'route_id': '37', 'route_name': 'Sedgwick'},
 {'route_id': '39', 'route_name': 'Pershing'},
 {'route_id': '43', 'route_name': '43rd'},
 {'route_id': '44', 'route_name': 'Wallace-Racine'},
 {'route_id': '47', 'route_name': '47th'},
 {'route_id': '48', 'route_name': 'South Damen'},
 {'route_id': '49', 'route_name': 'Western'},
 {'route_id': '49B', 'route_name': 'North Western'},
 {'route_id': 'X49', 'route_name': 'Western Express'},
 {'route_id': '50', 'route_name': 'Damen'},
 {'route_id': '51', 'route_name': '51st'},
 {'route_id': '52', 'route_name': 'Kedzie'},
 {'route_id': '52A', 'route_name': 'South Kedzie'},
 {'route_id': '53', 'route_name': 'Pulaski'},
 {'route_id': '53A', 'route_name': 'South Pulaski'},
 {'route_id': '54', 'route_name': 'Cicero'},
 {'route_id': '54A', 'route_name': 'North Cicero/Skokie Blvd.'},
 {'route_id': '54B', 'route_name': 'South Cicero'},
 {'route_id': '55', 'route_name': 'Garfield'},
 {'route_id': '55A', 'route_name': '55th/Austin'},
 {'route_id': '55N', 'route_name': '55th/Narragansett'},
 {'route_id': '56', 'route_name': 'Milwaukee'},
 {'route_id': '57', 'route_name': 'Laramie'},
 {'route_id': '59', 'route_name': '59th/61st'},
 {'route_id': '60', 'route_name': 'Blue Island/26th'},
 {'route_id': '62', 'route_name': 'Archer'},
 {'route_id': '62H', 'route_name': 'Archer/Harlem'},
 {'route_id': '63', 'route_name': '63rd'},
 {'route_id': '63W', 'route_name': 'West 63rd'},
 {'route_id': '65', 'route_name': 'Grand'},
 {'route_id': '66', 'route_name': 'Chicago'},
 {'route_id': '67', 'route_name': '67th-69th-71st'},
 {'route_id': '68', 'route_name': 'Northwest Highway'},
 {'route_id': '70', 'route_name': 'Division'},
 {'route_id': '71', 'route_name': '71st/South Shore'},
 {'route_id': '72', 'route_name': 'North'},
 {'route_id': '73', 'route_name': 'Armitage'},
 {'route_id': '74', 'route_name': 'Fullerton'},
 {'route_id': '75', 'route_name': '74th-75th'},
 {'route_id': '76', 'route_name': 'Diversey'},
 {'route_id': '77', 'route_name': 'Belmont'},
 {'route_id': '78', 'route_name': 'Montrose'},
 {'route_id': '79', 'route_name': '79th'},
 {'route_id': '80', 'route_name': 'Irving Park'},
 {'route_id': '81', 'route_name': 'Lawrence'},
 {'route_id': '81W', 'route_name': 'West Lawrence'},
 {'route_id': '82', 'route_name': 'Kimball-Homan'},
 {'route_id': '84', 'route_name': 'Peterson'},
 {'route_id': '85', 'route_name': 'Central'},
 {'route_id': '85A', 'route_name': 'North Central'},
 {'route_id': '86', 'route_name': 'Narragansett/Ridgeland'},
 {'route_id': '87', 'route_name': '87th'},
 {'route_id': '88', 'route_name': 'Higgins'},
 {'route_id': '90', 'route_name': 'Harlem'},
 {'route_id': '91', 'route_name': 'Austin'},
 {'route_id': '92', 'route_name': 'Foster'},
 {'route_id': '93', 'route_name': 'California/Dodge'},
 {'route_id': '94', 'route_name': 'California'},
 {'route_id': '95', 'route_name': '95th'},
 {'route_id': '96', 'route_name': 'Lunt'},
 {'route_id': '97', 'route_name': 'Skokie'},
 {'route_id': '100', 'route_name': 'Jeffery Manor Express'},
 {'route_id': '103', 'route_name': 'West 103rd'},
 {'route_id': '106', 'route_name': 'East 103rd'},
 {'route_id': '108', 'route_name': 'Halsted/95th'},
 {'route_id': '111', 'route_name': '111th/King Drive'},
 {'route_id': '111A', 'route_name': 'Pullman Shuttle'},
 {'route_id': '112', 'route_name': 'Vincennes/111th'},
 {'route_id': '115', 'route_name': 'Pullman/115th'},
 {'route_id': '119', 'route_name': 'Michigan/119th'},
 {'route_id': '120', 'route_name': 'Ogilvie/Streeterville Express'},
 {'route_id': '121', 'route_name': 'Union/Streeterville Express'},
 {'route_id': '124', 'route_name': 'Navy Pier'},
 {'route_id': '125', 'route_name': 'Water Tower Express'},
 {'route_id': '126', 'route_name': 'Jackson'},
 {'route_id': '134', 'route_name': 'Stockton/LaSalle Express'},
 {'route_id': '135', 'route_name': 'Clarendon/LaSalle Express'},
 {'route_id': '136', 'route_name': 'Sheridan/LaSalle Express'},
 {'route_id': '143', 'route_name': 'Stockton/Michigan Express'},
 {'route_id': '146', 'route_name': 'Inner Lake Shore/Michigan Exp.'},
 {'route_id': '147', 'route_name': 'Outer DuSable Lake Shore Exp.'},
 {'route_id': '148', 'route_name': 'Clarendon/Michigan Express'},
 {'route_id': '151', 'route_name': 'Sheridan'},
 {'route_id': '152', 'route_name': 'Addison'},
 {'route_id': '155', 'route_name': 'Devon'},
 {'route_id': '156', 'route_name': 'LaSalle'},
 {'route_id': '157', 'route_name': 'Streeterville/Taylor'},
 {'route_id': '165', 'route_name': 'West 65th'},
 {'route_id': '169', 'route_name': '69th-UPS Express'},
 {'route_id': '171', 'route_name': 'U. of Chicago/Hyde Park'},
 {'route_id': '172', 'route_name': 'U. of Chicago/Kenwood'},
 {'route_id': '192', 'route_name': 'U. of Chicago Hospitals Express'},
 {'route_id': '201', 'route_name': 'Central/Ridge'},
 {'route_id': '206', 'route_name': 'Evanston Circulator'}]